### ISSUE TITLE
Can use this XML and restore backup?

### ISSUE THREAD

**Issue by arielsrv** [hirakujira/ECG-Enabler#11]
I want to know, if It possible use this file (pslist) instead your tweak.

I don't have phone rooted.

iOS 14.3 / WatchOS 7.2

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>HKAtrialFibrillationDetectionOnboardingCompleted</key>
	<integer>1</integer>
	<key>HKElectrocardiogramOnboardingCompleted</key>
	<integer>4</integer>
</dict>
</plist>
```

**Comment by hirakujira** [comment]
yes you can.

https://hiraku.tw/2019/10/4951/

**Comment by arielsrv** [comment]
![image](https://user-images.githubusercontent.com/760657/102635164-b0c78200-4131-11eb-8933-991572498d04.png)

I have followed the tutorial, now the application does not appear @hirakujira :(

**Comment by hirakujira** [comment]
Maybe you should try to change HKElectrocardiogramOnboardingCompleted to 3 and try again.
I'm not 100% sure that HKElectrocardiogramOnboardingCompleted = 4 can work for people haven't activate before

**Comment by arielsrv** [comment]
Use the v2 file, you say use the v1?

I have not edited the files manually.

**Comment by hirakujira** [comment]
Yes, maybe you need to use v1 first. Sorry I'm not sure because the country I live just allow us to enable v1 officially on iOS 14.3. I can't test whether we need v1 first to upgrade v2.

**Comment by arielsrv** [comment]
I will try again with v1.

**Comment by arielsrv** [comment]
it does not work :(

**Comment by hirakujira** [comment]
Maybe Apple blocked this method again like watchOS 7.0 & 7.0.1... I'm only sure that v1 can upgrade to v2 with this method in my country...

**Comment by MrAndersonThomas** [comment]
not work

**Comment by corneliusbp** [comment]
Mine works the ecg app works but it's still asking me to setup atrial fibrillation notifications in the health app! Any suggestions?

**Comment by hirakujira** [comment]
> Mine works the ecg app works but it's still asking me to setup atrial fibrillation notifications in the health app! Any suggestions?

Ignore it. There's a x button to click and ignore.
