### ISSUE TITLE
dont letme config ECG

### ISSUE THREAD

**Issue by NoSoyNico** [hirakujira/ECG-Enabler#15]
hi, i have ios 14.3 iphone 12, watch s6 7.3.2, jailbreak uncover,
i install Hiraku Dev tweak ECG ENABLER and now in apple watch showme " config ECG on your phone" and in my phone cant configure ECG....

So, i do this steps:

1.- i delete the tweak..
i unpair watch and pair like new and still the same problem

2.- LDrestart
I unpair watch and pair whit backup and still the same problem

3.- Turn On phone in mode no jail.
unpair watch and pair like new, and still the same problem

i dont know what more can i do :(

PLEASE HELP

**Comment by hirakujira** [comment]
Duplicated with #12
