### ISSUE TITLE
Compatibility with iOS 12.1.2

### ISSUE THREAD

**Issue by riotdream** [hirakujira/ECG-Enabler#3]
Hi,

is possible that this tweak would work on iOS 12.1.1 on XS and watchOS 5.1.2 on S4?

My Country is listed on EER - Italy - but I can't install your package because your minimum version is 12.2

I've unpacked it, dunno if I can try to install it manually.

**Comment by hirakujira** [comment]
Hi this can’t not work on iOS 12.1.1 because Apple used a new way to verify whether the ECG can be enabled on 12.2+. (Which is more difficult to bypass than 12.1.1).

**Comment by riotdream** [comment]
It was iOS 12.1.2, so either if a lower version is a no go for ECG activation?

I'm out of time for upgrading to 12.4 with a jb, I'm staying on 12.1.2 with jb and hoping that a watch jb could resolve the situation.

Thanks for your answer.

**Comment by hirakujira** [comment]
iOS 12.1.1 below: No ECG function at all
iOS 12.1.1 - 12.1.4: Old method
iOS 12.2 - 13.x: New method

This tweak only works for new method.
For old method, “maybe” you only need to change the region in the settings app of your AppleWatch to United States.

**Comment by riotdream** [comment]
Ok, now I understand! Thank you so much @hirakujira.
