### ISSUE TITLE
IOS 13.4 and WatchOS 6.2

### ISSUE THREAD

**Issue by hadeshimself** [hirakujira/ECG-Enabler#4]
Have you tried or heard about anyone using this technique with the latest releases? It looks like theres something going on on the watch side where the ECG app is not being installed.

**Comment by hirakujira** [comment]
I will push an update for iOS 13.4 + watchOS 6.2. Maybe it will work.

**Comment by hadeshimself** [comment]
Thanks. Where should I get it? BigBoss or is there a way to update manually?

**Comment by hirakujira** [comment]
It will be available on BigBoss. But you can try it now and tell me whether it works. Just open Health → Heart → ECG after installation https://a.cl.ly/v1urZYEK

**Comment by hadeshimself** [comment]
I installed it and it behaves like the previous plist hack. The ECG activation screen with the birthday confirmation goes away but I don’t see the ECG app in the Watch. The watch was purchased on the US. Show I try to repair it?

**Comment by hirakujira** [comment]
You don't need to unpair it. Because I don't have any device which can be jailbroken on 13.4, I can't test whether it really works, I just researched the code and tried to patch it. However I build another version, could you try this again?

Also, if you see the birthday confirmation, just kill the Health app and open it again, try this 3~4 times, if it still not work, them this tweak doesn't work.

Updated DEB: https://a.cl.ly/NQuZ8Yp2

**Comment by hadeshimself** [comment]
Yes, it worked! I then removed the package because it would always get stuck at the birthday prompt. Thanks for your help. Let me know if you need further debug help.

**Comment by hirakujira** [comment]
> Yes, it worked! I then removed the package because it would always get stuck at the birthday prompt. Thanks for your help. Let me know if you need further debug help.

Could you answer these questions? Thanks!
1. After installation, do the birthday prompt shows?
2. Do you try to kill Health app and reopen again? How many times you do this?
3. How do you know it works? Because you checked on the watch instead of iPhone app?

**Comment by hadeshimself** [comment]
The birthday prompt doesn’t show, only the “Setup ECG...” button that leads to that check but clicking on that button would hang the app. I killed that app at least 5 times. I know it worked because the ECG app was missing on my watch and after this it finally appeared.
