### ISSUE TITLE
ECG app won’t re-install

### ISSUE THREAD

**Issue by ibrahimk157** [hirakujira/ECG-Enabler#5]
Hello there,

So previously, I tried the trick with iMazing where you replace a plist in the backup. And it activated ECG in the health app. However, the ECG app on my apple watch (which used to be there before doing this) disappeared completely and I was never able to get it to re-install. It doesn’t even show up when I try to download it from the AppStore.

So being desperate, I jailbroke and tried this tweak. Yet the ECG app on the watch still won’t show up! I’m using the latest version of the tweak which claims to have iOS 13.4 and watchos 6.2 support.

Here’s my setup:

iPhone X 256GB model A1901 iOS 13.4.1
Apple Watch Series 5 Aluminum 44mm GPS + Cellular (bought from the US) model A2095 WatchOS 6.2.1

No idea what to do now, I need your urgent help!

**Comment by hirakujira** [comment]
Try this deb please.
https://a.cl.ly/12uy6pK6

**Comment by ibrahimk157** [comment]
> Try this deb please.
> https://a.cl.ly/12uy6pK6

Now the health app crashes instantly when going to the ecg section

**Comment by ibrahimk157** [comment]
Oh wait!!! The ecg app is installing!!!

**Comment by ibrahimk157** [comment]
YES!!! Installed and working!!!!

Thank you soooo much!!!!

**Comment by ibrahimk157** [comment]
Ok i just ran into another issue

As soon as I uninstalled the tweak, the health app went back to trying to ask for activation. Same in the apple watch app.

**Comment by ibrahimk157** [comment]
Update: I had to do a bit of fiddling around.

I re-installed the deb you linked above, which re-activated the ecg app. I then downloaded the plist from here https://www.reddit.com/r/AppleWatch/comments/dhsbft/tutorial_apple_watch_ecg_activation_anywhere/?utm_source=amp&utm_medium=&utm_content=post_body and pasted it in /var/mobile/library/preferences

I then uninstalled the tweak and the ecg remained activated! 

Note: just pasting the plist alone without using this tweak only activates the ecg in the health app, but not the apple watch.

**Comment by ibrahimk157** [comment]
I wanted to also add:

I just tried restoring from a Apple Watch backup to get my stuff back. And sure enough, the ecg app is still there and is still activated!!!

**Comment by hirakujira** [comment]
OK I added the plist thing to the tweak again. Maybe it would fix this issue. However because you already activated, I need find someone else to test.

**Comment by hirakujira** [comment]
> > Try this deb please.
> > https://a.cl.ly/12uy6pK6
> 
> Now the health app crashes instantly when going to the ecg section

So how do you make it work?

**Comment by ibrahimk157** [comment]
> > > Try this deb please.
> > > https://a.cl.ly/12uy6pK6
> > 
> > 
> > Now the health app crashes instantly when going to the ecg section
> 
> So how do you make it work?

Here’s what I did step by step:

1) I installed the deb for the tweak

2) I noticed the health app crashes immediately when going to the ecg section 

3) then after a few seconds, the ecg app started downloading on my apple watch

4) I pasted the plist in the directory I mentioned above

5) I uninstalled the tweak

6) Now the health app no longer crashes and ecg is fully activated in both the health app and apple watch ecg


Note: when i skip adding the plist, the health app goes back to asking for the ecg activation as soon as I uninstall the tweak. Which also makes the ecg app on the watch ask to be activated.

**Comment by hirakujira** [comment]
Thanks for your detailed report, it's really useful for me to debug.

**Comment by ibrahimk157** [comment]
> Thanks for your detailed report, it's really useful for me to debug.

My pleasure! Thank you for this great tweak!
