### ISSUE TITLE
Issue with ECG enable tweak 

### ISSUE THREAD

**Issue by iQasim90** [hirakujira/ECG-Enabler#6]
Hi dear as per subject above i install ur tweak and follow ur instructions but still nothing working 
I try to follow the previous issue was posted here but I couldn't found any one help 
Before 6.2.5 version the ecg app was on my watch but after update its gone i try all thing to reinstall but can not 

Please help me to solve this issue 

Thanks

**Comment by hirakujira** [comment]
Update the tweak to v1.4.1
Go to Health.app → Heart → ECG on your iPhone, then check your Apple Watch. If it doesn't show, try to unpair and pair your Apple Watch again.

**Comment by iQasim90** [comment]
Thanks for ur quick response but already try brother 
I unpair and pair 3 times but nothing happened

**Comment by iQasim90** [comment]
Update 

Now its work thanks a lot 

Thanks with love

**Comment by hirakujira** [comment]
So how did you make it work?

**Comment by iQasim90** [comment]
Delete the tweak 
unpair and pair the watch 
after restart the device after
install tweak 
Ldrestart from pawerselector tweak 
And done
