### ISSUE TITLE
Compatibility with iOS 14

### ISSUE THREAD

**Issue by SoundBlaster** [hirakujira/ECG-Enabler#9]
I installed iOS 14.0.1 on my iPhone 6S, jailbroken it with checkra1n and install Cydia. When I try to install tweak Cydia says me "Depends iOS Firmware <13.4" - what is it? I see in source code 
```Depends: mobilesubstrate, firmware (>= 12.2)```
and
```
if (kCFCoreFoundationVersionNumber >= kCFCoreFoundationVersionNumber_iOS_13_4) {
        %init(BypassMPN);
    }
```

How can I install this tweak? Why does it have a strict top version of iOS? Can I build it and install by myself?

**Comment by SoundBlaster** [comment]
So, there is some bug in Cydia may be. I installed v1.4.1 with Installer from BigBoss repo.
But tweak has no effect on Health.app.

**Comment by SoundBlaster** [comment]
I try again & again and now it works. Thanks

**Comment by RAVEENSR** [comment]
After following steps like you did, Health app shows that open the ECG app in order to take a measurement. But in the watch, the ecg app is not there. Tried unpairing and pairing again(as a new watch), but this does not work. Any help?

**Comment by RAVEENSR** [comment]
@SoundBlaster Can you let me know the exact steps that you have followed to successfully activate ECG?

**Comment by chriscoderdr** [comment]
> After following steps like you did, Health app shows that open the ECG app in order to take a measurement. But in the watch, the ecg app is not there. Tried unpairing and pairing again(as a new watch), but this does not work. Any help?

I have the same problem, don't see the heart app anywhere in the watch, and I repaired it a couple of times with no luck.

**Comment by hirakujira** [comment]
Apple blocked this method on iOS 14. Maybe it will work in the future again.
(This method works on iOS 12.2(?) ~ iOS 13.3, doesn't work on iOS 13.4, but works again on iOS 13.5 ~ 13.7. Thus, it's possible that Apple blocks this on iOS 14.0 but reopen it later.)

**Comment by hirakujira** [comment]
It works for watchOS 7.0.2 + iOS 14.0.1 again. You can re-pair the Apple Watch to test
